import { Horse, HealthMetric, Alert } from './types';

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const initialHorses: Horse[] = [
  {
    id: 'horse-1',
    name: 'Thunder',
    breed: 'Arabian',
    age: 7,
    weight: 1100,
    gender: 'male',
    status: 'healthy',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: 'horse-2',
    name: 'Bella',
    breed: 'Quarter Horse',
    age: 4,
    weight: 950,
    gender: 'female',
    status: 'warning',
    createdAt: daysAgo(25),
    updatedAt: daysAgo(0),
  },
  {
    id: 'horse-3',
    name: 'Storm',
    breed: 'Thoroughbred',
    age: 12,
    weight: 1050,
    gender: 'male',
    status: 'healthy',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: 'horse-4',
    name: 'Luna',
    breed: 'Paint Horse',
    age: 6,
    weight: 980,
    gender: 'female',
    status: 'critical',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(0),
  },
];

export const initialHealthMetrics: HealthMetric[] = [
  {
    id: 'metric-1',
    horseId: 'horse-1',
    horseName: 'Thunder',
    temperature: 100.2,
    heartRate: 36,
    respiratoryRate: 12,
    weight: 1100,
    timestamp: daysAgo(1),
    assessment: {
      score: 95,
      status: 'healthy',
      findings: ['All vital signs within normal ranges', 'Heart rate optimal at 36 bpm', 'Temperature normal at 100.2°F'],
      recommendations: ['Continue regular monitoring', 'Maintain current diet and exercise routine'],
    },
  },
  {
    id: 'metric-2',
    horseId: 'horse-2',
    horseName: 'Bella',
    temperature: 102.5,
    heartRate: 42,
    respiratoryRate: 18,
    weight: 950,
    timestamp: daysAgo(0),
    assessment: {
      score: 62,
      status: 'warning',
      findings: ['Temperature elevated at 102.5°F (normal: 99–101°F)', 'Respiratory rate slightly elevated at 18 breaths/min', 'Heart rate near upper boundary'],
      recommendations: ['Monitor temperature every 4 hours', 'Ensure adequate hydration', 'Contact veterinarian if temperature exceeds 103°F', 'Reduce strenuous exercise until symptoms subside'],
    },
  },
  {
    id: 'metric-3',
    horseId: 'horse-3',
    horseName: 'Storm',
    temperature: 99.8,
    heartRate: 32,
    respiratoryRate: 10,
    weight: 1050,
    timestamp: daysAgo(2),
    assessment: {
      score: 92,
      status: 'healthy',
      findings: ['Vital signs within normal ranges', 'Temperature normal at 99.8°F', 'Heart rate steady at 32 bpm'],
      recommendations: ['Continue regular monitoring', 'Maintain current care routine'],
    },
  },
  {
    id: 'metric-4',
    horseId: 'horse-4',
    horseName: 'Luna',
    temperature: 101.0,
    heartRate: 22,
    respiratoryRate: 7,
    weight: 980,
    timestamp: daysAgo(0),
    assessment: {
      score: 28,
      status: 'critical',
      findings: ['Heart rate critically low at 22 bpm (normal: 28–44 bpm)', 'Respiratory rate below normal at 7 breaths/min (normal: 8–16)', 'Possible cardiac or respiratory issue'],
      recommendations: ['Contact veterinarian immediately', 'Keep horse calm and minimize movement', 'Monitor continuously until veterinarian arrives', 'Do not administer medication without vet guidance'],
    },
  },
];

export const initialAlerts: Alert[] = [
  {
    id: 'alert-1',
    horseId: 'horse-2',
    horseName: 'Bella',
    severity: 'warning',
    status: 'new',
    title: 'Elevated Temperature Detected',
    message: 'Bella\'s temperature recorded at 102.5°F, above the normal range of 99–101°F. Monitor closely and consider veterinary consultation.',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'alert-2',
    horseId: 'horse-4',
    horseName: 'Luna',
    severity: 'critical',
    status: 'new',
    title: 'Critical Low Heart Rate',
    message: 'Luna\'s heart rate recorded at 22 bpm, critically below the normal range of 28–44 bpm. Immediate veterinary attention required.',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'alert-3',
    horseId: 'horse-4',
    horseName: 'Luna',
    severity: 'critical',
    status: 'new',
    title: 'Low Respiratory Rate',
    message: 'Luna\'s respiratory rate at 7 breaths/min is below the normal range of 8–16 breaths/min. Urgent veterinary evaluation needed.',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'alert-4',
    horseId: 'horse-1',
    horseName: 'Thunder',
    severity: 'info',
    status: 'resolved',
    title: 'Routine Checkup Due',
    message: 'Thunder\'s annual routine health examination is due. Schedule an appointment with your veterinarian.',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: 'alert-5',
    horseId: 'horse-3',
    horseName: 'Storm',
    severity: 'info',
    status: 'acknowledged',
    title: 'Weight Monitoring Reminder',
    message: 'Storm is due for a routine weight check. Regular weight monitoring helps detect health issues early.',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
];
